### ISSUE TITLE
Unsafe use of sessionStorage throws in chrome

### ISSUE THREAD

**Issue by noahm** [astoilkov/use-storage-state#2]
This is a bit of an edge case, but it came up when attempting to roll this out at Twitch.

Chrome has an option at `chrome://settings/content/siteData` which is labeled as "Don't allow sites to save data on your device" which some users of twitch apparently have enabled (possibly by way of using more privacy focused chromium derivatives?). 

<img width="712" alt="Screenshot 2024-08-29 at 13 16 30" src="https://github.com/user-attachments/assets/4a36db9f-e225-4430-9ca6-b06ced444649">

With this selected, any attempts to access `localStorage` or `sessionStorage`, like [here](https://github.com/astoilkov/use-storage-state/blob/045e92e06422bff677db6f9a8b9301c90547d31e/src/useStorageState.ts#L55), will throw an exception. (The access of `localStorage` is guarded, but `sessionStorage` is not and causes the throw when not explicitly specifying a storage backend.)

I don't know if you want to bother supporting this Chrome configuration, so feel free to close this issue. I was able to easily work around this in our usage by building a safe wrapper object conforming to the `Storage` interface that I pass in via the `storage` option.

**Comment by astoilkov** [comment]
Yes, I'm interested in supporting this. I will fix this soon and release a new version. Thanks!

**Comment by astoilkov** [comment]
Quick question, this safe wrapper object you built — is it an empty implementation or does it do something?

**Comment by noahm** [comment]
My fallback case returns a bare-minimum working implementation of the Storage interface that just reads and writes values from a POJO in a closure. approximately:

```ts
function getMemoryStorage(): Storage {
  let items: Record<string, string> = {};
  return {
    getItem(key) { return items[key] },
    ...
  };
}
```

**Comment by astoilkov** [comment]
Done. I've published a new major release as this changes the way the library behaves by default.

**Comment by noahm** [comment]
This looks great! One caveat: Consumers intending to use session storage will still have to guard their own reference rather than simply passing `storage: sessionStorage`. I only wanted to call that out in case you wanted to document that in the example usage.

**Comment by astoilkov** [comment]
Hmm, your point made me think. It's not straightforward for the user to use `sessionStorage`. I've made some improvements and made it like so (61a4f1b9f22b07a49bbb642b7cff56533286e6b1). I will sleep on it and probably make a new major release:
```ts
useStorageState("key", {
  storage: "session",
  memoryFallback: true // true is the default, can now be disabled
})
```

The new idea is for the `storage` option to allow a literal that converts to trying to use the storage and using a fallback, if enabled.

**Comment by noahm** [comment]
Ah, simply selecting the storage backend with a string is definitely better for most. However for some use cases (large codebases like twitch) it may still be useful to have the option of passing our own custom storage implementation, even though it means we have to work around issues like Chrome's blocked storage ourselves. Do you think that's an option you could preserve in addition to passing a string?

**Comment by astoilkov** [comment]
Yes, that's part of the implementation. The new option accepts `"local"`, `"session"`, `Storage`, or `undefined`. You will still be able to use your own custom `Storage` implementation.
